apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanica-app
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-otel
          image: busybox:1.36
          command:
            - sh
            - -c
            - >-
              until nc -z otel-collector 4318; do echo waiting for otel-collector; sleep 2; done;
      containers:
        - name: mecanica-app
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fiap-mecanica:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
