name: Build & Push

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente (lab, prod, etc)'
        required: true
        type: string
        default: lab
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
        default: us-east-1
      ecr_repository:
        description: 'ECR Repository'
        required: true
        type: string
        default: "fiap-mecanica"

permissions:
  contents: read

jobs:
  build:
    name: 🏗️ Build & Push (SHA Tag)
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🏷️ Set Short SHA
        id: main_sha
        run: echo "main_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 🔨 Build Artifact
        run: mvn clean package -DskipTests --batch-mode --no-transfer-progress

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws_region }}

      - name: 🔑 Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🐳 Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repository }}
          IMAGE_TAG: ${{ steps.main_sha.outputs.main_sha }}
        run: |
          docker build \
            --file Dockerfile \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --label "git-commit=${{ github.sha }}" \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
