name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "lab"
      aws_region:
        required: true
        type: string
        default: "us-east-1"
      aws_account_id:
        required: false
        type: string
      eks_cluster_name:
        required: false
        type: string
        default: "fiap-cluster"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente (lab, prod, etc)'
        required: true
        type: string
        default: "lab"
      aws_region:
        description: 'AWS Region'
        required: true
        type: string
        default: "us-east-1"
      aws_account_id:
        description: 'Account ID AWS (opcional, necessário para cross-account)'
        required: false
        type: string
      eks_cluster_name:
        description: 'Nome do cluster EKS'
        required: true
        type: string
        default: "fiap-cluster"

jobs:
  deploy:
    name: 🚀 K8s Deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      AWS_REGION: ${{ inputs.aws_region }}
      AWS_CLUSTER_NAME: "${{ inputs.environment }}-${{ inputs.eks_cluster_name }}"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id || vars.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          echo "Using Cluster: ${AWS_CLUSTER_NAME}"
          aws eks update-kubeconfig \
            --region "${AWS_REGION}" \
            --name "${AWS_CLUSTER_NAME}"

      - name: 🔐 Setup K8S AWS Credentials Secret
        run: |
          kubectl create namespace external-secrets --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic aws-credentials -n external-secrets \
            --from-literal=aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --from-literal=aws_session_token=${{ secrets.AWS_SESSION_TOKEN }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: 🔐 Fetch DB Credentials from Secrets Manager
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id ${ENVIRONMENT}/mecanica/db \
            --query "SecretString" \
            --output text)

          echo "DB_HOST=$(echo $SECRET_JSON | jq -r .host)" >> $GITHUB_ENV
          echo "DB_USERNAME=$(echo $SECRET_JSON | jq -r .username)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(echo $SECRET_JSON | jq -r .password)" >> $GITHUB_ENV
          echo "DB_NAME=$(echo $SECRET_JSON | jq -r .dbname)" >> $GITHUB_ENV

      - name: Deploy to K8s
        run: ./scripts/k8s-deploy.sh
